DROP DATABASE CLINICA;

CREATE DATABASE CLINICA;

USE CLINICA;

CREATE TABLE MESSAGES (

ID INTEGER(10) PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
MOTIVATION VARCHAR(30) NOT NULL,
MESSAGE VARCHAR(4000) NOT NULL
);

INSERT INTO MESSAGES(NAME, EMAIL, MOTIVATION, MESSAGE)
VALUES('Mateus Ferreira', 'mateus.ferreira@email.com', 'Elogio','Estou deixando um feedback...');

CREATE TABLE ESPECIALITIES(
  ID INTEGER(10) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL
);

INSERT INTO ESPECIALITIES(NAME) VALUES('Clínico Geral');
INSERT INTO ESPECIALITIES(NAME) VALUES('Ortodontista');
INSERT INTO ESPECIALITIES(NAME) VALUES('Pediatra');

CREATE TABLE POSITIONS(
  ID INTEGER(10) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL
);

INSERT INTO POSITIONS(NAME) VALUES('Médico');
INSERT INTO POSITIONS(NAME) VALUES('Enfermeiro');
INSERT INTO POSITIONS(NAME) VALUES('Secretário');

CREATE TABLE COLLABORATORS (
  ID INTEGER(10) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  BIRTHDATE DATE NOT NULL,
  GENDER CHAR(1) NOT NULL,
  FAMILY VARCHAR(30) NOT NULL,
  POSITION INTEGER(10) REFERENCES POSITIONS,
  ESPECIALITY INTEGER(10) REFERENCES ESPECIALITIES,
  CPF VARCHAR(11) NOT NULL,
  RG VARCHAR(15) NOT NULL
);

CREATE TABLE COLLABORATOR_ADDRESS(
  COLLABORATOR INTEGER(10) REFERENCES COLLABORATORS,
  CEP VARCHAR(8) NOT NULL,
  ADDRESS_TYPE VARCHAR(20) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  NUMBER INTEGER(8),
  COMPLEMENT VARCHAR(100),
  DISTRICT VARCHAR(100),
  CITY VARCHAR(100) NOT NULL,
  STATE VARCHAR(100) NOT NULL,
  PRIMARY KEY (COLLABORATOR)
);

INSERT INTO COLLABORATORS (NAME, BIRTHDATE, GENDER, FAMILY, POSITION, ESPECIALITY, CPF, RG)
VALUES ('Oridia Caroliny', '1994-03-04', 'F', 'CASADO(A)', 2, NULL, '12345678910', 'RJ-107890');

INSERT INTO COLLABORATOR_ADDRESS (COLLABORATOR, CEP, ADDRESS_TYPE, ADDRESS, NUMBER, COMPLEMENT, DISTRICT, CITY, STATE)
VALUES ((SELECT MAX(ID) FROM COLLABORATORS), '38408202', 'RUA', 'JOÃO VELASCO DE ANDRADE', '407', 'APTO. 303', 'SANTA MÔNICA', 'UBERLÂNDIA', 'MINAS GERAIS');

