DROP DATABASE CLINICA;

CREATE DATABASE CLINICA;

USE CLINICA;

CREATE TABLE MESSAGES (

ID INTEGER(10) PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
MESSAGE VARCHAR(4000) NOT NULL
);

INSERT INTO MESSAGES(NAME, EMAIL, MESSAGE)
VALUES('Mateus Ferreira', 'mateus.ferreira@email.com', 'Estou deixando um feedback...');